# Generated by Django 4.2.16 on 2024-12-19 01:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0008_alter_election_end_time_alter_election_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstaff',
            name='can_access_candidates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminstaff',
            name='can_access_elections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminstaff',
            name='can_access_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminstaff',
            name='can_access_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminstaff',
            name='can_access_voters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminstaff',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_time',
            field=models.TimeField(default=datetime.time(3, 39, 19, 329936)),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_time',
            field=models.TimeField(default=datetime.time(1, 39, 19, 329920)),
        ),
    ]
