# Generated by Django 4.2.16 on 2024-12-20 00:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0010_remove_adminstaff_can_access_candidates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='fingerprint',
        ),
        migrations.AddField(
            model_name='voter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='fingerprint_image',
            field=models.ImageField(blank=True, null=True, upload_to='fingerprints/'),
        ),
        migrations.AddField(
            model_name='voter',
            name='fingerprint_template',
            field=models.TextField(blank=True, help_text='Processed fingerprint template data', null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='end_time',
            field=models.TimeField(default=datetime.time(2, 50, 14, 215416)),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 50, 14, 215398)),
        ),
    ]
