# Generated by Django 5.1.4 on 2025-01-05 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_remove_voter_user_alter_election_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='fingerprint_template',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_reg_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_time',
            field=models.TimeField(default=datetime.time(22, 53, 23, 576689)),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_time',
            field=models.TimeField(default=datetime.time(20, 53, 23, 576689)),
        ),
    ]
